### ISSUE TITLE
Parameter settings

### ISSUE THREAD

**Issue by SwcK423** [esw0116/ODGS#2]
Excuse me, I see that some hyperparameter settings in the repo are different from those in paper, and my experimental results show that the settings in the paper are much better, but will out of memory memory (RTX 3090). Could you please give a parameter setting that can match the performance in paper, or just use the current settings in this repo?

**Comment by esw0116** [comment]
Thank you for your valuable comment
We also often meet OOM messages during optimization with 24GB VRAM graphic cards.
This happens because a lot of Gaussians are needed to express the entire scene.
A one thing to prevent OOM would be increase the threshold to reduce the number of split/cloned Gaussians, but it will compromise the reconstruction performance.
Still our method can render images with novel view instantaneously while maintaining comparable or even better performance to EgoNeRF.
We will soon update the code to match the values in the paper.
